### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by bpjordan** [MoDNS/MoDNS#86]
Add support for HTTPS communication for the API & frontend

**Comment by bpjordan** [comment]
Will require a new server setting for certificate path.

Since users will likely be using a custom domain on their server, they will have to sign their own certificate (since TLS certificates are valid only for a certain domain).

For this same reason, we likely cannot ship with HTTPS enabled by default, and it will require a somewhat involved process for the user to get it set up. I'm open to suggestions on how we can make this process easier.

**Comment by carterray31001** [comment]
would forcing the domain to modns.local allow us to ship with it by default?

**Comment by bpjordan** [comment]
Something like that would work, but I'm not sure how to get the local DNS plugin able to detect the local IP address, and that would also cause issues for the Docker image (as the IP address visible to the server is different from the actual externally facing IP address).

If we got something like this working, we would likely need to include a command-line argument to enable/disable HTTPS for troubleshooting the connection

**Comment by carterray31001** [comment]
I'd be open to discussing that avenue.  If a user *really* wants a custom domain, they can implement their own custom domain intercepter plugin and deal with the https themselves. I'm leaning toward having the https for users who don't care about a custom domain name for their server.

**Comment by bpjordan** [comment]
Fair enough. The goal of the local DNS plugin is to make it easy for users to manage local DNS on a domain that they manage, which would default to .local. We should probably include a warning when doing this that it can mess up your HTTPS certs though.

**Comment by carterray31001** [comment]
and maybe we could provide a way for them to fix their certs if they change the domain

**Comment by bpjordan** [comment]
Yeah, that would make for a great addition to the tools page

**Comment by bpjordan** [comment]
So, upon further investigation, our approach of distributing pre-signed certificates for a default `modns.local` hostname would require we do one of the following:
- Get the default certificates signed by a 3rd party CA, which is [generally not possible for .local domains](https://superuser.com/questions/1257025/how-to-create-signed-certificate-for-a-local-name), or
- Create our own root Certificate Authority and require users to install the certificate for that new CA as a trusted certificate in their browser for all devices from which they access the frontend (which in addition to being a massive security risk to users is a pretty user-unfriendly installation process)

Both cases would also require that we store security credentials (i.e. the CA cert and/or TLS cert and key) for users' home networks publicly in this repository or otherwise distribute it publicly in packages, which is also an Insanely Bad Idea for security, with the added bonus of adding work for us to maintain the certificates, which must be periodically renewed regardless of which method we choose.

Meaning, there isn't a way for us to include a default implementation with HTTPS without a massive security compromise and some user unfriendliness, the two things we were hoping to avoid in the first place.

IMO, the best course of action is to move forward with HTTP as the default and HTTPS available, with instructions and tools for helping security-minded users set up HTTPS themselves using the methods I've described.

**Comment by carterray31001** [comment]
that's probably the best way to go given our options. It's really only necessary for situations involving paswords, so what about doing something like:
 - symmetric key where the key is created on install and stored in both frontend and backend (if the frontend can somehow store it privately)
 or
 - asymmetric key with the server having the public key generated at install

**Comment by bpjordan** [comment]
I'm pretty firmly against trying to implement our own security methods other than TLS. Anything we do will require some form of cumbersome user setup or sharing of secrets over some insecure channel, leaving us right back at square one, just with a bunch of added complexity and risk of added vulnerability. There is no perfect, secure solution that isn't going to involve some user setup, and my opinion is that if we're going to have to make users set up their own security, we should do it right. This is a view shared by (as far as I can tell) most security professionals (See [here](https://security.stackexchange.com/a/97056) and [here](https://security.stackexchange.com/a/18198)).

Instead of implementing our own security methods, we should be educating users about the risks of using HTTP and providing as much support as we can to simplify the process of enabling TLS.
